name: hello world from Python
on:
  workflow_dispatch:
    
jobs:
    hello-world-from-python:
        runs-on: ubuntu-latest  
        steps:
            - name: clone repo
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: Run hello.py
              run: python hello.py  
                           

